on:
  push:
    branches: [ main ]

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CLOUDWAYS_HOST }}      # Cloudways public IP
          username: ${{ secrets.CLOUDWAYS_USER }}    # App username
          password: ${{ secrets.CLOUDWAYS_PASS }}    # App password
          protocol: sftp                            # <— important
          port: 22
          local-dir: dist/
          server-dir: public_html/                  # where your site lives
          dangerous-clean-slate: false              # safer incremental uploads